# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{qadmin}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Quint"]
  s.date = %q{2009-10-27}
  s.description = %q{An [almost] one command solution for adding admin interfaces/resources to a Rails app.}
  s.email = ["aaron@quirkey.com"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "LICENSE",
     "PostInstall.txt",
     "README.rdoc",
     "Rakefile",
     "init.rb",
     "lib/qadmin.rb",
     "lib/qadmin/actions/create.erb",
     "lib/qadmin/actions/destroy.erb",
     "lib/qadmin/actions/edit.erb",
     "lib/qadmin/actions/index.erb",
     "lib/qadmin/actions/new.erb",
     "lib/qadmin/actions/show.erb",
     "lib/qadmin/actions/update.erb",
     "lib/qadmin/configuration.rb",
     "lib/qadmin/controller.rb",
     "lib/qadmin/form_builder.rb",
     "lib/qadmin/helper.rb",
     "lib/qadmin/overlay.rb",
     "lib/qadmin/page_titles.rb",
     "lib/qadmin/templates.rb",
     "lib/qadmin/views/default/edit.html.erb",
     "lib/qadmin/views/default/index.html.erb",
     "lib/qadmin/views/default/new.html.erb",
     "lib/qadmin/views/default/show.html.erb",
     "qadmin.gemspec",
     "rails/init.rb",
     "rails_generators/qadmin/USAGE",
     "rails_generators/qadmin/qadmin_generator.rb",
     "rails_generators/qadmin/templates/_form.html.erb",
     "rails_generators/qadmin/templates/_instance.html.erb",
     "rails_generators/qadmin/templates/controller.rb",
     "rails_generators/qadmin/templates/functional_test.rb",
     "rails_generators/qadmin/templates/images/icon_asc.gif",
     "rails_generators/qadmin/templates/images/icon_desc.gif",
     "rails_generators/qadmin/templates/images/icon_destroy.png",
     "rails_generators/qadmin/templates/images/icon_edit.png",
     "rails_generators/qadmin/templates/images/icon_export.png",
     "rails_generators/qadmin/templates/images/icon_find.png",
     "rails_generators/qadmin/templates/images/icon_import.png",
     "rails_generators/qadmin/templates/images/icon_list.png",
     "rails_generators/qadmin/templates/images/icon_new.png",
     "rails_generators/qadmin/templates/images/icon_next.gif",
     "rails_generators/qadmin/templates/images/icon_prev.gif",
     "rails_generators/qadmin/templates/images/icon_show.png",
     "rails_generators/qadmin/templates/images/icon_sort.png",
     "rails_generators/qadmin/templates/images/indicator_medium.gif",
     "rails_generators/qadmin/templates/layout.html.erb",
     "rails_generators/qadmin/templates/style.css",
     "script/console",
     "script/destroy",
     "script/generate",
     "script/txt2html",
     "test/test_generator_helper.rb",
     "test/test_helper.rb",
     "test/test_qadmin_configuration.rb",
     "test/test_qadmin_controller.rb",
     "test/test_qadmin_generator.rb"
  ]
  s.homepage = %q{http://github.com/quirkey/qadmin}
  s.post_install_message = %q{PostInstall.txt}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{quirkey}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{An [almost] one command solution for adding admin interfaces/resources to a Rails app.}
  s.test_files = [
    "test/test_generator_helper.rb",
     "test/test_helper.rb",
     "test/test_qadmin_configuration.rb",
     "test/test_qadmin_controller.rb",
     "test/test_qadmin_generator.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_runtime_dependency(%q<will_paginate>, [">= 2.3.7"])
      s.add_runtime_dependency(%q<restful_query>, [">= 0.2.0"])
      s.add_development_dependency(%q<rake>, ["~>10.4", ">= 10.4.2"])
      s.add_development_dependency(%q<shoulda>, [">= 1.2.0"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_dependency(%q<rake>, ["~>10.4", ">= 10.4.2"])
      s.add_dependency(%q<restful_query>, [">= 0.2.0"])
      s.add_dependency(%q<shoulda>, [">= 1.2.0"])
      s.add_dependency(%q<will_paginate>, [">= 2.3.7"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.2"])
    s.add_dependency(%q<rake>, ["~>10.4", ">= 10.4.2"])
    s.add_dependency(%q<restful_query>, [">= 0.2.0"])
    s.add_dependency(%q<shoulda>, [">= 1.2.0"])
    s.add_dependency(%q<will_paginate>, [">= 2.3.7"])
  end
end
