# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: qadmin 0.2.3 ruby lib
$LOAD_PATH.unshift "lib"
require "qadmin/version"

Gem::Specification.new do |s|
  s.name = "qadmin"
  s.version = Qadmin::VERSION

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Aaron Quint"]
  s.date = "2009-04-07"
  s.description = "An [almost] one command solution for adding admin interfaces/resources to a Rails app."
  s.email = ["aaron@quirkey.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Appraisals",
    "Gemfile",
    "History.txt",
    "LICENSE",
    "PostInstall.txt",
    "README.rdoc",
    "Rakefile",
    "init.rb",
    "lib/qadmin.rb",
    "lib/qadmin/actions/create.erb",
    "lib/qadmin/actions/destroy.erb",
    "lib/qadmin/actions/edit.erb",
    "lib/qadmin/actions/index.erb",
    "lib/qadmin/actions/new.erb",
    "lib/qadmin/actions/show.erb",
    "lib/qadmin/actions/update.erb",
    "lib/qadmin/configuration.rb",
    "lib/qadmin/controller.rb",
    "lib/qadmin/form_builder.rb",
    "lib/qadmin/helper.rb",
    "lib/qadmin/overlay.rb",
    "lib/qadmin/page_titles.rb",
    "lib/qadmin/railtie.rb",
    "lib/qadmin/templates.rb",
    "lib/qadmin/util.rb",
    "lib/qadmin/views/default/_instance.html.erb",
    "lib/qadmin/views/default/_pagination.html.erb",
    "lib/qadmin/views/default/edit.html.erb",
    "lib/qadmin/views/default/index.html.erb",
    "lib/qadmin/views/default/new.html.erb",
    "lib/qadmin/views/default/show.html.erb",
    "qadmin.gemspec",
    "rails/init.rb",
    "rails_generators/qadmin/USAGE",
    "rails_generators/qadmin/qadmin_generator.rb",
    "rails_generators/qadmin/templates/_form.html.erb",
    "rails_generators/qadmin/templates/_instance.html.erb",
    "rails_generators/qadmin/templates/controller.rb",
    "rails_generators/qadmin/templates/functional_test.rb",
    "rails_generators/qadmin/templates/images/icon_asc.gif",
    "rails_generators/qadmin/templates/images/icon_desc.gif",
    "rails_generators/qadmin/templates/images/icon_destroy.png",
    "rails_generators/qadmin/templates/images/icon_edit.png",
    "rails_generators/qadmin/templates/images/icon_export.png",
    "rails_generators/qadmin/templates/images/icon_find.png",
    "rails_generators/qadmin/templates/images/icon_import.png",
    "rails_generators/qadmin/templates/images/icon_list.png",
    "rails_generators/qadmin/templates/images/icon_new.png",
    "rails_generators/qadmin/templates/images/icon_next.gif",
    "rails_generators/qadmin/templates/images/icon_prev.gif",
    "rails_generators/qadmin/templates/images/icon_show.png",
    "rails_generators/qadmin/templates/images/icon_sort.png",
    "rails_generators/qadmin/templates/images/indicator_medium.gif",
    "rails_generators/qadmin/templates/layout.html.erb",
    "rails_generators/qadmin/templates/style.css",
    "test/configuration_test.rb",
    "test/controller_test.rb",
    "test/generator_helper.rb",
    "test/generator_test.rb",
    "test/helper.rb",
    "test/util_test.rb"
  ]
  s.homepage = "http://github.com/quirkey/qadmin"
  s.post_install_message = "PostInstall.txt"
  s.rubyforge_project = "quirkey"
  s.rubygems_version = "2.2.2"
  s.summary = "An [almost] one command solution for adding admin interfaces/resources to a Rails app."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_runtime_dependency(%q<erubis>, [">= 2.7.0", "~> 2.7"])
      s.add_runtime_dependency(%q<iconv>, [">= 1.0.3"])
      s.add_runtime_dependency(%q<restful_query>, [">= 0.2.0"])
      s.add_runtime_dependency(%q<will_paginate>, [">= 2.3.7"])
      s.add_development_dependency(%q<appraisal>, [">= 1.0.2", "~> 1.0"])
      s.add_development_dependency(%q<minitest>, [">= 5.5.0", "~> 5.5"])
      s.add_development_dependency(%q<mocha>, [">= 1.1.0", "~> 1.1"])
      s.add_development_dependency(%q<rake>, [">= 10.4.2", "~> 10.4"])
      s.add_development_dependency(%q<rails>, [">= 2.3.2"])
      s.add_development_dependency(%q<rubigen>, [">= 1.5.7"])
      s.add_development_dependency(%q<shoulda>, [">= 1.2.0"])
      s.add_development_dependency(%q<sqlite3>, [">= 1.3.10", "~> 1.3"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_dependency(%q<erubis>, [">= 2.7.0", "~> 2.7"])
      s.add_dependency(%q<iconv>, [">= 1.0.3"])
      s.add_dependency(%q<restful_query>, [">= 0.2.0"])
      s.add_dependency(%q<will_paginate>, [">= 2.3.7"])
      s.add_dependency(%q<appraisal>, [">= 1.0.2", "~> 1.0"])
      s.add_dependency(%q<minitest>, [">= 5.5.0", "~> 5.5"])
      s.add_dependency(%q<mocha>, [">= 1.1.0", "~> 1.1"])
      s.add_dependency(%q<rake>, [">= 10.4.2", "~> 10.4"])
      s.add_dependency(%q<rails>, ["< 3", ">= 2.3.2"])
      s.add_dependency(%q<rubigen>, [">= 1.5.7"])
      s.add_dependency(%q<shoulda>, [">= 1.2.0"])
      s.add_dependency(%q<sqlite3>, [">= 1.3.10", "~> 1.3"])
    end
  else
    s.add_dependency(%q<activesupport>, ["< 3", ">= 2.3.2"])
    s.add_dependency(%q<erubis>, [">= 2.7.0", "~> 2.7"])
    s.add_dependency(%q<iconv>, [">= 1.0.3"])
    s.add_dependency(%q<restful_query>, [">= 0.2.0"])
    s.add_dependency(%q<will_paginate>, [">= 2.3.7"])
    s.add_dependency(%q<appraisal>, [">= 1.0.2", "~> 1.0"])
    s.add_dependency(%q<minitest>, [">= 5.5.0", "~> 5.5"])
    s.add_dependency(%q<mocha>, [">= 1.1.0", "~> 1.1"])
    s.add_dependency(%q<rake>, [">= 10.4.2", "~> 10.4"])
    s.add_dependency(%q<rails>, [">= 2.3.2"])
    s.add_dependency(%q<rubigen>, [">= 1.5.7"])
    s.add_dependency(%q<shoulda>, [">= 1.2.0"])
    s.add_dependency(%q<sqlite3>, [">= 1.3.10", "~> 1.3"])
  end
end
