# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
$LOAD_PATH.unshift "lib"

require "qadmin"

Gem::Specification.new do |s|
  s.name = "qadmin"
  s.version = Qadmin::VERSION

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Quint"]
  s.date = "2009-04-07"
  s.description = "An [almost] one command solution for adding admin interfaces/resources to a Rails app."
  s.email = ["aaron@quirkey.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = Dir.glob("{rails_generators}/**/*") + Dir.glob("{rails}/**/*") + Dir.glob("{lib}/**/*") + Dir.glob("{test}/**/*") + %w{History.txt LICENSE PostInstall.txt README.rdoc Rakefile init.rb}
  s.homepage = "http://github.com/quirkey/qadmin"
  s.post_install_message = "PostInstall.txt"
  s.require_paths = ["lib"]
  s.rubyforge_project = "quirkey"
  s.rubygems_version = "1.8.23"
  s.summary = "An [almost] one command solution for adding admin interfaces/resources to a Rails app."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_runtime_dependency(%q<erubis>, ["~> 2.7", ">= 2.7.0"])
      s.add_runtime_dependency 'iconv', '~> 1.0'
      s.add_runtime_dependency 'will_paginate', '~> 2.3', '>= 2.3.7'
      s.add_runtime_dependency 'restful_query', '~> 0.2', '>= 0.2.0'
      s.add_development_dependency(%q<appraisal>, ["~>1.0", ">= 1.0.2"])
      s.add_development_dependency(%q<minitest>, ["~> 5.5", ">= 5.5.0"])
      s.add_development_dependency(%q<mocha>, ["~> 1.1", ">= 1.1.0"])
      s.add_development_dependency(%q<rake>, ["~>10.4", ">= 10.4.2"])
      s.add_development_dependency(%q<rails>, [">= 2.3.2", "< 3"])
      s.add_development_dependency 'rubigen', '~> 1.5', '>= 1.5.7'
      s.add_development_dependency 'shoulda', '~> 1.2', '>= 1.2.0'
      s.add_development_dependency(%q<sqlite3>, ["~> 1.3", ">= 1.3.10"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.2", "< 3"])
      s.add_dependency(%q<appraisal>, ["~>1.0", ">= 1.0.2"])
      s.add_dependency(%q<erubis>, ["~> 2.7", ">= 2.7.0"])
      s.add_dependency 'iconv', '~> 1.0'
      s.add_dependency(%q<minitest>, ["~> 5.5", ">= 5.5.0"])
      s.add_dependency(%q<mocha>, ["~> 1.1", ">= 1.1.0"])
      s.add_dependency(%q<rake>, ["~>10.4", ">= 10.4.2"])
      s.add_dependency(%q<rails>, [">= 2.3.2", "< 3"])
      s.add_dependency 'restful_query', '~> 0.2', '>= 0.2.0'
      s.add_dependency 'rubigen', '~> 1.5', '>= 1.5.7'
      s.add_dependency 'shoulda', '~> 1.2', '>= 1.2.0'
      s.add_dependency(%q<sqlite3>, ["~> 1.3", ">= 1.3.10"])
      s.add_dependency 'will_paginate', '~> 2.3', '>= 2.3.7'
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.2", "< 3"])
    s.add_dependency(%q<appraisal>, ["~>1.0", ">= 1.0.2"])
    s.add_dependency(%q<erubis>, ["~> 2.7", ">= 2.7.0"])
    s.add_dependency 'iconv', '~> 1.0'
    s.add_dependency(%q<minitest>, ["~> 5.5", ">= 5.5.0"])
    s.add_dependency(%q<mocha>, ["~> 1.1", ">= 1.1.0"])
    s.add_dependency(%q<rake>, ["~>10.4", ">= 10.4.2"])
    s.add_dependency(%q<rails>, [">= 2.3.2", "< 3"])
    s.add_dependency 'restful_query', '~> 0.2', '>= 0.2.0'
    s.add_dependency 'rubigen', '~> 1.5', '>= 1.5.7'
    s.add_dependency 'shoulda', '~> 1.2', '>= 1.2.0'
    s.add_dependency(%q<sqlite3>, ["~> 1.3", ">= 1.3.10"])
    s.add_dependency 'will_paginate', '~> 2.3', '>= 2.3.7'
  end
end
